routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view(
        'welcome',
        [
            'title' => "An even cooler way to do the title"
        ]
    );
});

/*
    Route::get('home', function ()
    {
        return view('home');
    })->middleware('auth');
*/


//This is used to check if pages can be views by non authenticated users.
Route::group(['middleware' => ['auth']], function () {
    Route::resource('assets', 'AssetController');
    Route::resource('home', 'HomeController');
    Route::resource('jobs', 'JobsController');
    Route::resource('incidents', 'IncidentController');

    Route::resource('organisation', 'OrganisationController');
    Route::resource('sites', 'SiteController');
    Route::resource('users', 'UserController');
    Route::resource('userPaid', 'UserController');
    Route::resource('categories', 'CategoryController');
    Route::resource('account', 'AccountController');
});



//Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Route::get('/register', 'Auth\RegisterController@index')->name('register');



/* Testing */

Route::get('/page', function () {
    return view(
        'testing.page',
        [
            'title' => "Page 2 - A little about the Author",
            'author' => json_encode([
                "name" => "Fisayo Afolayan",
                "role" => "Software Enginner",
                "code" => "Always keeping it clean"
            ])
        ]
    );
});


Route::get('/spa', function () {
    return view('testing.vueapp');
})->where('any', '.*');

app/Incident.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Incident extends Model
{
    protected $fillable = [
    
        'severity', 'cost', 'name'

    ];



    public function job()
    {
        return $this->hasOne('App\Job');
    }


    public function site(){
        return $this->belongsTo('App\Site');
    }
}

app/Http/Controllers/IncidentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Incident;
use Log;
use App\Organisation;
use App\Site;
use App\Job;

class IncidentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organisations = Organisation::all();
        $incidents = Incident::all();
        return view('incident.incidentIndex', compact('incidents', 'organisations'));
    }


    public function incident(Request $request)
    {
        $id = $request->input('id');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        //
        //$organisation = Organisation::all();
        //$var = $request->get('organisation_id');
        //$sites = Site::where('organisation_id', $var)
        //->get();
        $organisations = Organisation::all();
        //$var = $request->get('organisation_id');
        //$sites = Site::where('organisation_id', $var)
        //->get();
        $sites = Site::all();
        return view('incident.createIncident', compact('sites', 'organisations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'severity' => 'required', 
        ]);       

        $incident = new Incident([
        
            'severity' => $request->get('severity'),
            'name' => $request->get('name'),
           
        ]);
            
        Log::info('This is the check of incident var:' . $incident);
        Log::info('This is the check of incident var name:' . $incident->get('name'));
        Log::info('This is the check of name:' . $incident->name);
        Log::info('This is the request check:' . $request->get('name'));
        Log::info($incident);

        $site = Site::find($request->get('site_id'));
        $organisation = Organisation::find($request->get('organisation_id'));

        $incident->site()->associate($site);
        $incident->save();
        

        return redirect('home')->with('success', 'A manager will look at your request shortly');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $incidents = Incident::find($id);
        return view('incident.displayOneIncident', compact('incidents'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $incidents = Incident::find($id);
        Log::info('IncidentController Edit');
        return view('incident.editIncident', compact('incidents'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $incidents = Incident::find($id);
        $incidents->severity = $request->get('severity');
        $incidents->save();

        return redirect('/incidents')->with('success', 'The incident has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $incidents = Incident::find($id);
        $incidents->delete();

        return redirect('/incidents')->with('success', 'incident deleted!');
    }
}

resources/views/incident/createIncident.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a Incident</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    
      <form method="post" action="{{ route('incidents.store') }}">
          @csrf
          
          <div class="form-group">    
              <label for="organisation_id">Organisation</label>
             
              <select name="organisation_id">
              @foreach($organisations as $organisation)
                <option value="{{$organisation->id}}">{{$organisation->name}}</option> 
              @endforeach
                </select> 
          </div>
{{--TO DO--}}
{{-- Lift in Organisation ID based off user }}
{{--JS: Make Sites auto populate based of organisation_id--}}

          <div class="form-group">    
              <label for="site_id">Site</label>
              <select name="site_id">
              @foreach($sites as $site)
                <option value="{{$site->id}}">{{$site->location}}</option>
                @endforeach
                </select> 
          </div>
          
          <div class="form-group">
              <label for="name">Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>

          <div class="form-group">
              <label for="severity">Severity:</label>
              <input type="text" class="form-control" name="severity"/>
          </div>


<button type="submit" href="{{ route('incidents.store', ['organisation_id'=>$site->organisation->id, 'site_id'=>$site->id]) }}" class="btn btn-primary-outline">Add Incident</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/incident/displayOneIncident.blade.php
@extends('layouts.nav') 
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">View an Incident</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('incidents.show', $incidents->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="severity">Severity:</label>
                <label for="severitys">{{ $incidents-> severity }}:</label>
            </div>

            <div class="form-group">
                <label for="cost">Cost:</label>
                <label for="cost">{{ $incidents-> cost }}:</label>
            </div>

            <div class="form-group">
                <label for="job_complete">Job Complete:</label>
                <label for="job_complete">{{ $incidents-> job_complete}}:</label>
            </div>
        </form>
    </div>
</div>

resources/views/incident/editIncident.blade.php
@extends('layouts.nav') 
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update Order</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif

        <form method="post" action="{{ route('incidents.update', $incidents->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="severity">Severity:</label>
                <input type="text" class="form-control" name="severity" value={{ $incidents->severity }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/incident/incidentIndex.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Incident</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Organisation</td>
          <td>Severity</td>
          <td>Name</td>
        </tr>
    </thead>
    <div>
    <a style="margin: 19px;" href="{{ route('incidents.create')}}" class="btn btn-primary">New Incident</a>
    </div>  
    <tbody>
        @foreach($incidents as $incident) 
         <tr>
        
        <td>{{$incident->site->organisation->name}} </td>
      
        {{--Make this display actual org for incidents--}}

            <td>{{$incident->severity}}</td>
            <td>{{$incident->name}}</td>
            <td>
                <a href="{{ route('incidents.edit',$incident->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <a href="{{ route('incidents.show',$incident->id)}}" class="btn btn-primary">Display</a>
            </td>
            <td>
                <form action="{{ route('incidents.destroy', $incident->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                </td>
        </tr>
        @endforeach
    </tbody>
  </table>

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection