routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view(
        'welcome',
        [
            'title' => "An even cooler way to do the title"
        ]
    );
});

/*
    Route::get('home', function ()
    {
        return view('home');
    })->middleware('auth');
*/


//This is used to check if pages can be views by non authenticated users.
Route::group(['middleware' => ['auth']], function () {
    Route::resource('assets', 'AssetController');
    Route::resource('home', 'HomeController');
    Route::resource('jobs', 'JobsController');
    Route::resource('incidents', 'IncidentController');

    Route::resource('organisation', 'OrganisationController');
    Route::resource('sites', 'SiteController');
    Route::resource('users', 'UserController');
    Route::resource('userPaid', 'UserController');
    Route::resource('categories', 'CategoryController');
    Route::resource('account', 'AccountController');
});



//Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Route::get('/register', 'Auth\RegisterController@index')->name('register');



/* Testing */

Route::get('/page', function () {
    return view(
        'testing.page',
        [
            'title' => "Page 2 - A little about the Author",
            'author' => json_encode([
                "name" => "Fisayo Afolayan",
                "role" => "Software Enginner",
                "code" => "Always keeping it clean"
            ])
        ]
    );
});


Route::get('/spa', function () {
    return view('testing.vueapp');
})->where('any', '.*');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $fillable = [
        'user_id', 'incident_id', 'status', 'date', 'cost',
    ];


    public function incident()
    {
        return $this->belongsTo('App\Incident');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function status()
    {
        return $this->belongsTo('App\Status');
    }
}

app/Http/Controllers/JobsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Incident;
use App\User;
use App\Organisation;
use App\Job;
use App\Site;
use App\Role;
use App\Status;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use Log;

class JobsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index(Request $request) 
    {
        if($request->get('status')  == NULL) {
            $jobs =Job::all();
        }else {
            $jobs = Job::where('status', $request->get('status'))->get();
        }        
        $current_user = Auth::user();

        if ($current_user->level_of_access == 2) {
            $newJobs = array();
            foreach ($jobs as $job) {
                if ($job->user == $current_user) {
                    array_push($newJobs, $job);
                }
            }
            $jobs = $newJobs;
        }
        return View('jobs.jobIndex', compact('jobs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $organisation = Organisation::all();
        $sites = Site::all();
        $incidents = Incident::all();
        return view('jobs.createJobs', compact('organisation', 'sites', 'incidents'));
    }
    /**Stores
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*** Creation of JOB obj from incident ***/
        $job = new Job([

            'description' => $request->get('name'),
        ]);
        Log::info('Request log:' . $request);
        Log::info('Get name log:' . $request->get('name'));
        $incident = Incident::find($request->get('incident_id'));
        Log::info('Incident ID log:' . $request->get('incident_id'));


        $job->incident()->associate($incident);
        Log::info('Job Log:' . $job);
        $job->save();

        //Validation against adding multiple jobs for 1 incident

        return redirect('jobs')->with('success', 'Job saved');
    }

    /*
      Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        //
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    //This will be used by contractors to update job status && Cost calls update
    //call view edit contractorJobs View here
    public function edit($id, Request $request)
    {
        Log::info($id);
        $job = Job::find($id); 
        Log::info('ID check' . $job);
        $status = Status::all(); 
        $users = User::where('level_of_access', 2)->get();
        return view('jobs.updateJob', compact('job', 'users', 'status'));
    }//edit


    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    //Function used by edit JOB to update cost & status e.g. In-Progress to Complete

    public function update($id, Request $request)
    {
        Log::info('Job ID: ' .$id);
        Log::info('Status: ' .$request->get('status'));
        Log::info('User ID: ' .$request->get('user_id'));
        
        Log::info('Description From Contractor: ' .$request->get('description'));
        Log::info('Cost From Contractor:: ' .$request->get('cost'));

        $job = Job::find($id);
        Log::info('Job Check: ' . $job);
        $user = Auth::user();
        $status = Status::all();
        
        if($request->has('description')||$request->has('cost')){
            //contractor updating job
            $job->cost = $request->get('cost');
            $job->description = $request->get('description');
            $job->save();
            return redirect('/jobs');
        } else {
             //this section updates status
            $user->available = false;
            $job->user_id = $request->get('user_id');
            Log::info('User ID check Job assign' .$job->user_id);
            
           foreach($status as $status){
                if($status->id == $request->get('status')){
                    $status = $status;
                    $job->status_id = $status->id;
                }//IF
            }//for

            
            $job->save();
            return redirect('/jobs');
        }
    } //update

    public function displayPreviousJobs()
    {
        return view('jobs.displayPrevious');
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    // Not used all job completed can be viewed via reports
    public function destroy($id)
    {
        $job = Job::find($id);
        $job->delete();

        return redirect('/jobs')->with('success', 'job deleted!');
    }


    public function getIncidents()
    {
        $incidents = Incident::all();
        Log::info('DOING SOMETHING');
        return response()->json($incidents);
    }

    public function updateInformation(Request $request)
    {
        $incident = Incident::find($request->incident_id);
        $site = Site::find($incident->site_id);
        $organisation = Organisation::find($site->organisation_id);




        Log::info('[JobsController] update Information - Incident: ' . $incident);

        //   return response($incident->jsonSerialize());

        return Response::json(array(
            'incident' => $incident,
            'site' => $site,
            'organisation' => $organisation
        ));
    }
}

resources/views/jobs/createJobs.blade.php
      @extends('layouts.nav')

      @section('content')
      <div id="app">
          <create-job></create-job>
      </div>
      @endsection

resources/views/jobs/displayPrevious.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Job</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
      <br />
    @endif     
                  
          {{--If any job where status==complete && has user_id == AuthUser display table ...}}
        
        <h2 class="display-3">Previous Jobs</h2>
    <table class="table table-striped">
    <thead>

    </thead>
            {{--Previous Jobs:
            organisation->name
            site->location
            job->description
            user->hours
            job->date--}}
    <tbody> 
    
    </tbody>
    </table>


    </div>
</div>
@endsection

resources/views/jobs/jobIndex.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Jobs</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Organisation</td>
          <td>Location</td>
          <td>Severity</td>
          <td>Inital Description</td>
          <td>Description</td>
          <td>Date</td>
          <td>Cost</td>
          <td>Status</td>
        </tr>
    </thead>
    @if(Auth::user()->level_of_access == 3 || Auth::user()->level_of_access == 4)
                     
    <a style="margin: 19px;" href="{{ route('jobs.index', ['status'=> 'assigned']) }}" class="btn btn-primary">Jobs In Progress</a>

                <a style="margin: 19px;" href="{{ route('jobs.index', ['status'=> 'unassigned']) }}" class="btn btn-primary">Jobs to Assign</a>

                <a style="margin: 19px;" href="{{ route('jobs.index', ['status'=> '']) }}" class="btn btn-primary">All Jobs</a>

    <a style="margin: 19px;" href="{{ route('jobs.create')}}" class="btn btn-primary">Create Job</a>
    @endif
    <tbody>
@foreach ($jobs as $job) 
<tr>
      <td>{{$job->id}}</td>
      <td>{{$job->incident->site->organisation->name}}</td>
      <td>{{$job->incident->site->location}} </td>
      <td>{{$job->incident->severity}} </td>
      <td>{{$job->incident->name}} </td>
      <td>{{$job->description}} </td>
      <td>{{$job->date}} </td>
      <td>{{$job->cost}} </td>
      <td>{{$job->status->type}} </td>
      @if(Auth::user()->level_of_access == 3 || Auth::user()->level_of_access == 4)
      <td><form action="{{ route('jobs.destroy', $job->id)}}" method="post">
          @csrf
          @method('DELETE')
          <button class="btn btn-danger" style="margin: 19px;" type="submit">Delete</button>
      </form></td>
      @endif
      <td><a style="margin: 19px;" href="{{ route('jobs.edit', [$job->id, 'status'=>$job->status] )}}" class="btn btn-primary">Update Status</a></td>

</tr>
@endforeach
    </tbody>
  </table>

                        <td>{{$job->incident->site->organisation->name}}</td>
                        <td>{{$job->incident->site->location}} </td>
                        <td>{{$job->incident->severity}} </td>
                        <td>{{$job->incident->name}} </td>
                        <td>{{$job->description}} </td>
                        <td>{{$job->date}} </td>
                        <td>{{$job->cost}} </td>
                        <td>{{$job->status}} </td>
                        <td>

                        <td>
                            <form action="{{ route('jobs.destroy', $job->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>

                        <td><a style="margin: 19px;" href="{{ route('jobs.edit', [$job->id, 'status'=>$job->status] )}}" class="btn btn-primary"></a>Update Status</td>
                    </tr>
                    @endforeach
                </tbody>
        </table>

        @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
        @endif
    </div>
</div>
@endsection

resources/views/jobs/updateJob.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Assign Jobs</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
      <br />
    @endif
   <form method="post" action="{{ route('jobs.update', $job->id, 'user_id', 'status', 'description', 'cost')  }}">
   @method('PATCH')
          @csrf 
          @if(Auth::user()->level_of_access == 3 || Auth::user()->level_of_access == 4)
         
          <div class="form-group">
        <label for="job_id">Job ID:</label>
        <label for="job_id">{{ $job->id }}</label>
        </div>

          <div class="form-group">
        <label for="description">Job Name:</label>
        <label for="description">{{ $job->incident->name }}</label></div>

        <div class="form-group">
        <label for="severity">Severity:</label>
        <label for="severity">{{ $job->incident->severity}}</label></div>

        <div class="form-group">
        <label for="organisation_name">Organisation Name</label>
        <label for="organisation_name">{{$job->incident->site->organisation->name}}</label></div>

          <div class="form-group">
          <label for="location">Location</label>
          <label for="location">{{$job->incident->site->location}}</label></div>

          <div class="form-group">
          <label for="user_id">Contractor:</label>
          <select name ="user_id">
          @foreach ($users as $user)
          <option value="{{$user->id}}">{{$user->name}}</option> 
          @endforeach
          </select>
          </div>

          <div class="form-group">
          <label for="status">Status:</label>
          <select name ="status">
          @foreach ($status as $status)
          <option value="{{$status->id}}">{{$status->type}}</option> 
          @endforeach
          </select>
          
          </div>

          @else 
          <table class="table table-striped">
    <thead>
    <td>Job ID</td>
    <td>Organisation Name </td>
    <td>Location </td>
    <td>Initial Description</td>
    <td>Updated Description</td>
    <td>Cost</td>
    </thead>

    <tbody> 
    <td>{{$job->id }}</td>
    <td>{{$job->incident->site->organisation->name}} </td>
    <td>{{$job->incident->site->location}} </td>
    <td>{{$job->incident->name}} </td>
    <td>{{$job->description}} </td>
    <td>{{$job->cost}} </td>

    </tbody>
    </table>

    <div class="form-group">
    <label for="description">Description:</label>
    <input type="text" class="form-control" name="description" value='{{ $job->description }}' />
    </div>

    <div class="form-group">
    <label for="cost">Cost:</label>
    <input type="text" class="form-control" name="cost" value='{{ $job->cost }}' />
    </div>
    <button type="submit"  class="btn btn-primary-outline">Complete</button> 
    
          @endif
            <button type="submit"  class="btn btn-primary-outline">Update</button> 
      </form>

      

</div>
</div>
@endsection