routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view(
        'welcome',
        [
            'title' => "An even cooler way to do the title"
        ]
    );
});

/*
    Route::get('home', function ()
    {
        return view('home');
    })->middleware('auth');
*/


//This is used to check if pages can be views by non authenticated users.
Route::group(['middleware' => ['auth']], function () {
    Route::resource('assets', 'AssetController');
    Route::resource('home', 'HomeController');
    Route::resource('jobs', 'JobsController');
    Route::resource('incidents', 'IncidentController');

    Route::resource('organisation', 'OrganisationController');
    Route::resource('sites', 'SiteController');
    Route::resource('users', 'UserController');
    Route::resource('userPaid', 'UserController');
    Route::resource('categories', 'CategoryController');
    Route::resource('account', 'AccountController');
});



//Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Route::get('/register', 'Auth\RegisterController@index')->name('register');



/* Testing */

Route::get('/page', function () {
    return view(
        'testing.page',
        [
            'title' => "Page 2 - A little about the Author",
            'author' => json_encode([
                "name" => "Fisayo Afolayan",
                "role" => "Software Enginner",
                "code" => "Always keeping it clean"
            ])
        ]
    );
});


Route::get('/spa', function () {
    return view('testing.vueapp');
})->where('any', '.*');

app/Organisation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organisation extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'type',

    ];
    
    public function site()
    {
        return $this->hasMany('App\Site');
    }
    /* 
    protected $table = 'organisations';
    protected $primaryKey = 'id';

    public function site()
    {
        return $this->hasMany('Site', 'id');
    }
*/
}


   

app/Http/Controllers/OrganisationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Organisation;
use App\Site;
use Log;

class OrganisationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organisations = Organisation::all();
        return view('organisation.viewOrganisations', compact('organisations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $organisations = Organisation::all();
        return view('organisation.createOrganisation', compact('organisations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            
        ]);
        $organisations = new Organisation([ 
            
            'name' => $request->get('name'), 
            'type' => $request->get('type'),
        ]);
        $organisations->save();
        
        
        return redirect('organisation')->with('success', 'organisation saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $organisations = Organisation::find($id);
        return view('organisation.editOrganisation', compact('organisations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $organisations = Organisation::find($id);
        $organisations->name = $request->get('name');
        $organisations->type = $request->get('type');
        
        $organisations->save();

        return redirect('/organisation')->with('success', 'The site has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $organisations = Organisation::find($id);
        $organisations->delete();

        return redirect('/organisation')->with('success', 'site deleted!');
    }
}

resources/views/organisation/createOrganisation.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add Organisation</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
   <form method="post" action="{{ route('organisation.store') }}">
          @csrf
          <div class="form-group">    
              <label for="name">Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>

          <div class="form-group">
              <label for="type">Type:</label>
              <input type="text" class="form-control" name="type"/>
          </div>


          <button type="submit" class="btn btn-primary-outline">Add Organisation</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/organisation/createSite.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Create Site</h1>
        <div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif

            <form method="post" action="{{ route('sites.store') }}">

                @csrf
                <div class="form-group">
                    <label for="organisation_id">Organisation</label>
                    <select name="organisation_id">
                        @foreach($organisations as $organisation)
                        <option value="{{$organisation->id}}">{{$organisation->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="location">Location</label>
                    <input type="text" class="form-control" name="location" />
                </div>

                <div class="form-group">
                    <label for="contact_num">Contact Number:</label>
                    <input type="text" class="form-control" name="contact_num" />
                </div>

                <div class="form-group">
                    <label for="manager_contact_number">Manager Number:</label>
                    <input type="text" class="form-control" name="manager_contact_number" />
                </div>

                <button type="submit" href="{{ route('sites.store', ['organisation_id'=>$organisation->id]) }}" class="btn btn-primary-outline">Add Site</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/organisation/editOrganisation.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update an Organisation</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('organisation.update', $organisations->id) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value={{ $organisations->name }} />
            </div>

            <div class="form-group">
                <label for="type">Type:</label>
                <input type="text" class="form-control" name="type" value={{ $organisations->type }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/organisation/editSite.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a Site</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('sites.update', $site->id) }}">
            @method('PATCH')
            @csrf

            <div class="form-group">
                <label for="location">Location:</label>
                <input type="text" class="form-control" name="location" value={{ $site->location }} />
            </div>

            <div class="form-group">
                <label for="contact_num">contact_num:</label>
                <input type="text" class="form-control" name="contact_num" value={{ $site->contact_num }} />
            </div>

            {{--<div class="form-group">
                <label for="manager_contact_num">Cost:</label>
                <input type="text" class="form-control" name="manager_contact_num" value={{ $site->manager_contact_num }} />
    </div>--}}
    <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
</div>
@endsection

resources/views/organisation/viewOrganisations.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Organisation</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Name</td>
          <td>Type</td>
        </tr>
    </thead> 
    </div>  
              <div>
              <a style="margin: 19px;" href="{{ route('organisation.create')}}" class="btn btn-primary">New Organisation</a>
              <a style="margin: 19px;" href="{{ route('sites.create')}}" class="btn btn-primary">New Sites</a>
              </div>  
        </div> 
    <tbody>
        @foreach($organisations as $organisation)
        <tr>
            <td>{{$organisation->name}}</td>
            <td>{{$organisation->type}}</td>
            <td><a href="{{ route('organisation.edit',$organisation->id)}}" class="btn btn-primary">Edit Organisation</a></td>
            <td>
                <form action="{{ route('organisation.destroy', $organisation->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                </td>
            <td> <a style="margin: 19px;" href="{{ route('sites.index', ['organisation_id'=>$organisation->id]) }}" class="btn btn-primary">Display Sites</a> </td>
        </tr>

        @endforeach
    </tbody>
  </table>

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection

resources/views/organisation/viewSites.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
    <div class="col-sm-12">
        <h1 class="display-3">Sites</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>Organisation</td>
                    <td>Location</td>
                    <td>Number</td>
                    <td>Manager Number</td>
                </tr>
            </thead>

            <tbody>
                @foreach($sites as $site)
                <tr>
                    <td>{{$organisation->name}}</td>
                    <td>{{$site->location}}</td>
                    <td>{{$site->contact_num}}</td>
                    {{--<td>{{$user->contact_number}}</td>--}}
                    <td> <a style="margin: 19px;" href="{{ route('sites.edit',$site->id)}}" class="btn btn-primary">Edit Site</a> </td>
                    <td>
                        <form action="{{ route('sites.destroy', $site->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach

            </tbody>
        </table>

        @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
        @endif
    </div>
</div>
@endsection