routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view(
        'welcome',
        [
            'title' => "An even cooler way to do the title"
        ]
    );
});

/*
    Route::get('home', function ()
    {
        return view('home');
    })->middleware('auth');
*/


//This is used to check if pages can be views by non authenticated users.
Route::group(['middleware' => ['auth']], function () {
    Route::resource('assets', 'AssetController');
    Route::resource('home', 'HomeController');
    Route::resource('jobs', 'JobsController');
    Route::resource('incidents', 'IncidentController');

    Route::resource('organisation', 'OrganisationController');
    Route::resource('sites', 'SiteController');
    Route::resource('users', 'UserController');
    Route::resource('userPaid', 'UserController');
    Route::resource('categories', 'CategoryController');
    Route::resource('account', 'AccountController');
});



//Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

//Route::get('/register', 'Auth\RegisterController@index')->name('register');



/* Testing */

Route::get('/page', function () {
    return view(
        'testing.page',
        [
            'title' => "Page 2 - A little about the Author",
            'author' => json_encode([
                "name" => "Fisayo Afolayan",
                "role" => "Software Enginner",
                "code" => "Always keeping it clean"
            ])
        ]
    );
});


Route::get('/spa', function () {
    return view('testing.vueapp');
})->where('any', '.*');

app/Asset.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Asset extends Model
{
    protected $fillable = [

        'asset_code', 'name', 'cost', 'category_id',

    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/AssetController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Asset;
use App\Category;
use Log;

class AssetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $assets = Asset::all();
        $categories = Category::all();
        Log::info('AssetController Index');
        return view('assets.assetIndex', compact('assets', 'categories'));
    } 

    /**
     * Show the form for creating a new resource.
     *asset_code", "name", "cost", "category_type
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        Log::info('AssetController Create');
        return view('assets.createAsset', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info('AssetController Store');

        $request->validate([
            'asset_code'=>'required',
            'name' => 'required',
            'cost' => 'required',
            
        ]);
        Log::info($request);
        $asset = new Asset([
            'asset_code' => $request->get('asset_code'),
            'name' => $request->get('name'),
            'cost' => $request->get('cost'),
        ]);
        Log::error($request->get('category_id'));
        $categories = Category::find($request->get('category_id'));
        Log::error($categories);
        $asset->category()->associate($categories);
        $asset->save();
        return redirect('assets')->with('success', 'asset saved');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $assets = Asset::find($id);
        return view('assets.displayOneAsset', compact('assets'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $assets = Asset::find($id);
        Log::info('AssetController Edit');
        return view('assets.editAsset', compact('categories', 'assets'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
{
        $assets = Asset::find($id);
        $categories = Category::find($id);
        $assets->asset_code =  $request->get('asset_code');
        $assets->name = $request->get('name');
        $assets->cost = $request->get('cost');
        $categories = Category::find($request->get('category_id'));
        $assets->save();

        return redirect('/assets')->with('success', 'The asset has been updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $assets = Asset::find($id);
        $assets->delete();

        return redirect('/assets')->with('success', 'asset deleted!');
    }
}

resources/views/assets/assetIndex.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">{{ __('Assets') }}</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Asset-Code</td>
          <td>Name</td>
          <td>Category </td>
          <td>Cost</td>
        </tr>
    </thead>
    <div>
    <a style="margin: 19px;" href="{{ route('assets.create')}}" class="btn btn-primary">New Asset</a>
    </div>  
    <tbody>
        @foreach($assets as $asset)
        @foreach($categories as $category)
        <tr>
            <td>{{$asset->asset_code}}</td>
            <td>{{$asset->name}}</td>
            <td>{{$category->type}}</td>       
            <td>{{$asset->cost}}</td>

            <td>
                <a href="{{ route('assets.edit',$asset->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <a href="{{ route('assets.show',$asset->id)}}" class="btn btn-primary">Display</a>
            </td>
            <td>
                <form action="{{ route('assets.destroy', $asset->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                </td>
        </tr>
        @endforeach
        @endforeach
    </tbody>
  </table>

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection

resources/views/assets/createAsset.blade.php
@extends('layouts.nav')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Add Asset To Order</h1>
        <div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <form method="post" action="{{ route('assets.store') }}">
                @csrf
                <div class="form-group">
                    <label for="asset_code">Asset Code:</label>
                    <input type="text" class="form-control" name="asset_code" />
                </div>

                <div class="form-group">
                    <label for="category_id">category:</label>
                    <select name="category_id">
                        @foreach($categories as $category)
                        <option value="{{$category->id}}">{{$category->type}}</option>
                        @endforeach
                    </select>
                </div>


                <div class="form-group">
                    <label for="name">name:</label>
                    <input type="text" class="form-control" name="name" />
                </div>

                <div class="form-group">
                    <label for="cost">cost:</label>
                    <input type="text" class="form-control" name="cost" />
                </div>


                <button type="submit" class="btn btn-primary">Add Asset</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/assets/displayOneAsset.blade.php
@extends('layouts.nav')
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">View an Asset</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('assets.show', $assets->id) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="asset_code">Asset Code:</label>
                <label for="costs">{{ $assets->asset_code }}:</label>
            </div>

            <div class="form-group">
                <label for="name">Name:</label>
                <label for="name">{{ $assets->name }}:</label>
            </div>

            <div class="form-group">
                <label for="cost">Cost:</label>
                <label for="costs">{{ $assets->cost }}:</label>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/assets/editAsset.blade.php
@extends('layouts.nav')
@Section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update an Asset</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('assets.update', $assets->id) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="asset_code">Asset Code:</label>
                <input type="text" class="form-control" name="asset_code" value={{ $assets->asset_code }} />
            </div>

            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value={{ $assets->name }} />
            </div>

            <div class="form-group">
                <label for="cost">Cost:</label>
                <input type="text" class="form-control" name="cost" value={{ $assets->cost }} />
            </div>

            <div class="form-group">
                <label for="category_id">Category:</label>
                <select name="category_id">
                    @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->type}}</option>
                    @endforeach
                </select>
            </div>



            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection